services:
  mysql:
    image: mysql:8.3.0
    container_name: salon_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - app

  eurekaserver:
    image: "naals/eureka-server-yt:v1"
    platform: linux/amd64
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent eurekaserver:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    container_name: eurekaserver
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - app


networks:
  app:
    driver: "bridge"

volumes:
  mysql: