services:
  mysql:
    image: mysql:8.3.0
    container_name: salon_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - app

  eurekaserver:
    image: "naals/eureka-server-yt:v1"
    platform: linux/amd64
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent eurekaserver:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    container_name: eurekaserver
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - app


  user-service:
    image: "naals/user-service-yt-sa:v1"
    platform: linux/amd64
    ports:
      - "5001:5001"
    healthcheck:
      test: "curl --fail --silent user-service:5001/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    container_name: user-service-sa
    environment:
      SPRING_APPLICATION_NAME: "user-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/sb_user_db"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
    depends_on:
      mysql:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - app

  salon-service:
    image: "naals/salon-service-yt-sa:v1"
    platform: linux/amd64
    ports:
      - "5002:5002"
    healthcheck:
      test: "curl --fail --silent salon-service:5002/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    container_name: salon-service-sa
    environment:
      SPRING_APPLICATION_NAME: "salon-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/sb_salon_db"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
    depends_on:
      mysql:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - app

  category-service:
    image: "naals/category-service-yt-sa:v1"
    platform: linux/amd64
    ports:
      - "5003:5003"
    healthcheck:
      test: "curl --fail --silent category-service:5003/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    container_name: category-service-sa
    environment:
      SPRING_APPLICATION_NAME: "category-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/sb_category_db"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
    depends_on:
      mysql:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - app

networks:
  app:
    driver: "bridge"

volumes:
  mysql: