spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/sb_payment_db
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 5002
